### ISSUE TITLE
能否提供一些字节数组到字节数组的编码和解码的api

### ISSUE THREAD

**Issue by SagoLu** [lexluthors/CompressTools-Android#12]
我打算做一个安卓同屏的项目，想使用webp来减少带宽，只是这个项目提供的api都有IO操作，
一次编码的时间在200-300毫秒左右，速度已经很快了，我觉得如果没有IO可能会更快，希望作者考虑一下。

**Comment by SagoLu** [comment]
尴尬了，我在模拟器上只花了6毫秒，是我手机太辣鸡

**Comment by lexluthors** [comment]
@Dragons-yu O(∩_∩)O~

**Comment by SagoLu** [comment]
性能较差的真机确实很慢，作者还是可以考虑一下，这样能适用更多的场景
