### ISSUE TITLE
抄袭！！！Fork别人的就好了，为什么要说成自己写的？

### ISSUE THREAD

**Issue by imkarl** [lexluthors/CompressTools-Android#7]

**Comment by robinxdroid** [comment]
@ImKarl 哪都能看到你，骚ke，作者可能借鉴别人代码忘了说Thanks，但是希望把标题去了。“安卓图片压缩终极解决方案，可能是最接近微信图片压缩的库，采用底层压缩。”这句话让人看了确实不舒服，之前的luban项目因为类似标题让人喷惨了

**Comment by ImKarl** [comment]
连名字都要借鉴吗？好歹把@author改了吧

**Comment by lexluthors** [comment]
@ImKarl 我是看过你发的这个项目，你仔细看清楚，我用的是包，他用的是什么？现在基本所有的开源框架都是build模式，难道build还有其他的写法？名字里面确实有相同的地方，但是不能说是抄袭吧！我写build模式一样可以写出来！难道我换个名字你就说不是抄袭了？你告诉我压缩的英文怎么拼，我换个名字！我用的这个so库，是我两三年前就用的，只不过我一直没有开放出来，现在我用as重新开放出来而已。网上可能也有和我类似的。兄弟，你发的这个项目里面的方法网上都能搜到，是不是也是抄袭？既然你说方法名字相同，那我就改一下！但是还是build模式。你让其他所有框架都别用这个模式，我就不用了。file文件处理的通用类网上到处都是，这个你发的项目也有，是不是抄袭的？

**Comment by ImKarl** [comment]
那么你怎么解释连注释都是抄的，而且连名字都抄

![myhpf5ndkpse](https://user-images.githubusercontent.com/3197744/34330504-8d2e9bbe-e958-11e7-878c-097df99a70f8.png)

**Comment by lexluthors** [comment]
@ImKarl 我跟你说了，你没看到？我说了，我看过你发的项目，这些通用工具类，我只不过是不想从新写一遍而已。这都是通用写法，有什么不一样！我再写一遍注上自己的名字有什么意义？不是还被你冠上抄袭的名号？这个项目的作者有些类也是网上复制的，只不过名字改成了他的，他就不是抄袭了是吧？我复制过来忘了改名字就是抄袭？你的意思是，他复制的改了名字算他的，我从他那复制的就是算他的，如果我从网上复制一份就算我的是吧？这个我没有改名字确实是忘记了，当时就想快点发出来，方便大家使用。但是里面的核心和他不同就够了。

**Comment by ImKarl** [comment]
jni 都是用的`libjpeg-turbo`，java就4个类  还是拷贝别人的。
那你是做了什么？
换了个名字吗？
还是说，你自己写了个`libjpeg`？

**Comment by ImKarl** [comment]
就算你做了些改动，用fork不行吗？尊重下原作者不好吗？

**Comment by alexykuan** [comment]
。。。。不要太在意这些，@ImKarl 如果他能持续完善这个库，我想这应该算是自己写的了吧。这里只提和技术相关的issue吧。Build Soft Together

**Comment by lexluthors** [comment]
@ImKarl 你项目里很多方法都是拷贝的，你注了别人名字没有？这只是改动的事吗？你项目里面复制的别人的改了我立马把项目里面改了。libjpeg你告诉我该写谁的名字？真搞笑。我有写自己写的libjpeg吗？我做了什么，我是封装一下，方便使用。你写的库难道不是封装便于使用？我问你你造出过什么创新的方法没有？我从头到尾也没写这是自己写出的libjpeg，不像你这种，复制的方法都写自己的，然后封装一下就是自己造的。也搞不清你是多厉害了，还是在这充大神，你的几个项目我看了，你告诉我有什么技术难点吗？还是有什么技术含量？我不图任何名利，就是拿出来给别人用的，谁想用，谁用，谁要是想改就改！你的库我能找到很多不是你的东西。我在这里也不想给你讨论这种问题，这里是讨论技术。其他问题可以直接发邮件！

**Comment by ImKarl** [comment]
我还是不知道你做了什么，是改了个名字吗？
用fork不行吗？尊重下原作者不好吗？

**Comment by lexluthors** [comment]
@ImKarl 没看出来只能说脑子有问题。回去好好看看你自己的那个项目，全部是抄袭那两个项目，里面的类都是从里面复制的，类名字都没改，就把别人的名字改成自己的了。真他妈贱逼啊。下面写个thanks就是自己的了？

**Comment by ImKarl** [comment]
单纯的封装，导入别人的源码。
我会尊重原作者，你能不能也尊重下呢？

**Comment by lexluthors** [comment]
@ImKarl 看清楚我和nanchen的方式一样不？不懂不要吓喷！通用操作类方法大家都一样！

**Comment by imkarl** [comment]
既然你可以删评论，那我也赖得说你、大家心知肚明就行

**Comment by lexluthors** [comment]
我的实现方式要是和nanchen不一样死你全家！一些sb总认为使用网上的通用方法也是抄袭，nanchen用的file类我就不能用？我们公司项目里面和他的也一样的，是不是抄的？真是遇到sb了，你项目中那么多通用操作类怎么不是抄袭？怎么没有注上别人的名字？

**Comment by imkarl** [comment]
所有，注释一样到底是怎么回事？
